classdef InstrumentRegistry
    methods (Static)
        function registry = all()
            registry = struct();

            registry.keysight_n9020a_esa = struct( ...
                'displayName', "Keysight N9020A", ...
                'resourceName', "TCPIP0::192.168.1.45::inst0::INSTR", ...
                'type', "ESA", ...
                'ip', "192.168.1.45");

            registry.ceyear_osa_6362d_white = struct( ...
                'displayName', "Ceyear 6362D White", ...
                'resourceName', "TCPIP0::192.168.1.35::8000::SOCKET", ...
                'type', "OSA", ...
                'ip', "192.168.1.35", ...
                'port', 8000, ...
                'unitColor', "white");

            registry.ceyear_osa_6362d_black = struct( ...
                'displayName', "Ceyear 6362D Black", ...
                'resourceName', "TCPIP0::192.168.1.36::10001::SOCKET", ...
                'type', "OSA", ...
                'ip', "192.168.1.36", ...
                'port', 10001, ...
                'unitColor', "black");

            registry.keysight_e5080b_vna = struct( ...
                'displayName', "Keysight E5080B", ...
                'resourceName', "TCPIP0::192.168.1.27::inst0::INSTR", ...
                'type', "VNA", ...
                'ip', "192.168.1.27");

            registry.siglent_sna5003x_e_vna = struct( ...
                'displayName', "SIGLENT SNA5003X-E", ...
                'resourceName', "TCPIP0::192.168.1.103::inst0::INSTR", ...
                'type', "VNA", ...
                'ip', "192.168.1.103");

            registry.keysight_mso9404a_scope = struct( ...
                'displayName', "Keysight MSO9404A", ...
                'resourceName', "TCPIP0::192.168.1.25::inst0::INSTR", ...
                'type', "Scope", ...
                'ip', "192.168.1.25");

            registry.rigol_dho4204_scope = struct( ...
                'displayName', "Rigol DHO4204", ...
                'resourceName', "TCPIP::192.168.1.49::INSTR", ...
                'type', "Scope", ...
                'ip', "192.168.1.49");
        end

        function entry = get(key)
            registry = labdevices.core.InstrumentRegistry.all();
            fieldName = char(string(key));
            if ~isfield(registry, fieldName)
                error("labdevices:UnknownInstrumentKey", ...
                    "Unknown instrument key: %s", fieldName);
            end
            entry = registry.(fieldName);
        end

        function resourceName = resource(key)
            entry = labdevices.core.InstrumentRegistry.get(key);
            resourceName = string(entry.resourceName);
        end
    end
end
